config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :confirmations => "confirmations",
                                       :passwords => "passwords",
                                       :sessions => "sessions" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # mount Ckeditor::Engine => '/ckeditor'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/admin/sidekiq'
  get '/triggers_test/', :to => 'triggers_test#triggers_test'

  root 'home#index'
  resources :brands
  resources :users, except: [:destroy, :index] do
    member do
      get :favorites
      get :goods
      patch :set_password
      delete :destroy_social_account
      delete :delete_avatar
    end
  end
  resources :products, except: [:index] do
    collection do
      post 'get_subcategories'
      post 'get_details'
    end
  end

  resources :categories, only: [:show]

  resources :photos, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]

  resources :shops, :controller => :shops do
    collection do
      post :update_shop_cover
    end
  end

  resources :promo_items, only: [:create, :update, :show] do
    member do
      get 'notify'
    end
  end

  controller :payments do
    post 'notify', as: :notify
  end

  post '/liqpay_payment' => 'payments#liqpay_payment'

  resources :conversations, only: [:index, :show, :create, :destroy]

  controller :static do
    get 'about', as: :about
    get 'condition', as: :condition
    get 'faq', as: :faq
    get 'contacts', as: :contacts
    get 'why_muzpoint', as: :why_muzpoint
    get 'how_advertising_works', as: :how_advertising_works
    get 'terms_of_use', as: :terms_of_use
  end

  resources :subscribers, :only => [:create]
  resources :feedbacks, :only => [:create]


  get '/countries', to: 'countries#index', as: :countries, controller: "countries"
  get '/countries/:id', to: 'countries#show', as: :country, controller: "countries"

  get '/cities', to: 'cities#index', as: :cities, controller: "cities"
  get '/countries/:country_id/:state_id/:id', to: 'cities#show', as: :city, controller: "cities"

  get '/categories/:category_id/:id', to: 'subcategories#show', as: :subcategory, controller: "subcategories"

  get '404', :to => 'errors#page_not_found'
  get '500', :to => 'errors#server_error'
  get '/:category_id/:id', to: redirect("/categories/%{category_id}/%{id}", status: 301)
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base

  belongs_to :user
  belongs_to :product

  after_create { FavoritesAddEvent.notify_user self.id }

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @product = Product.find(params[:product_id])
    @favorite = Favorite.new(:product => @product, :user => current_user)
    respond_to do |format|
      if @favorite.save
        format.js { render 'success', layout: false }
      else
        format.js { render 'error', layout: false }
      end
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @product = @favorite.product
    respond_to do |format|
      if @favorite.destroy
        format.html{ redirect_to :back }
        format.js { render 'success', layout: false }
      else
        format.html{ redirect_to :back }
        format.js { render 'error', layout: false }
      end
    end
  end

end

app/views/favorites/_favorite.slim
.product-price
  span Цена 
  = "$" + number_to_currency(@product.price)

- if user_signed_in?
  - unless @product.shop.user_id == current_user.id
    - if Favorite.find_by(:user => current_user, :product => @product).blank?
      = link_to favorites_path(:product_id => @product.id), :method => "POST", remote: true, :class => "button button-favorite"
        span.button-favorite__add
          i.icon-heart
          | Добавить в избранное
    - else
      = link_to Favorite.find_by(:user => current_user, :product => @product), :method => "DELETE", remote: true, :class => "button button-favorite button-favorite_pressed"
        span.button-favorite__favorite
          i.icon-heart
          | В избранном
        span.button-favorite__remove
          | Удалить из избранного

  .product-favorited
    = "Следят за товаром " + @product.favorites.count.to_s

app/views/favorites/success.js.erb
$('#favorites_container').html('<%= render "favorite" %>')